### PR TITLE
[GEP-18] Make CA certificate data key configurable

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind enhancement
/merge squash

**What this PR does / why we need it**:
As part of https://github.com/gardener/gardener/issues/3292#issuecomment-1036058890, the CA bundle secrets should be used which may contain both old and new CA certificate during rotation. However, such bundle secrets expose the data under `.data["bundle.crt"]` despite of `.data["ca.crt"]`, so the data key should be configurable for users.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/3292#issuecomment-1036058890

**Special notes for your reviewer**:
/cc @ishan16696 

**Release note**:

```noteworthy developer
The CA data key is now configurable under `.spec.etcd.tls.tlsCASecretRef.dataKey`. It still defaults to `ca.crt` if not provided.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Well, I just learned that this is not enough and that there is another place where this path is hard-coded (https://github.com/gardener/etcd-custom-image/blob/a0a4a3ec484c1bf8cee28459073f34bcc3e9d6c4/etcd_bootstrap_script.sh#L8)...

**Comment by ishan16696** [comment]
> until https://github.com/gardener/etcd-custom-image/pull/11 got merged and released

ok, we don’t  have any plans to release a `etcd-custom` image , do you want to have a release for `etcd-custom-image` ?

**Comment by rfranzke** [comment]
Yeah, this PR/change will only work after https://github.com/gardener/etcd-custom-image/pull/11 got merged because the `ca.crt` key is hard-coded there as well

**Comment by rfranzke** [comment]
> /hold until [gardener/etcd-custom-image#11](https://github.com/gardener/etcd-custom-image/pull/11) got merged and released

/unhold

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Comment by ishan16696** [comment]
Right now our scaffold tests for `etcd-druid` got failed. We are right now fixing that. I will merge this PR once our scaffolds test get pass.

**Comment by ishan16696** [comment]
Hi @rfranzke ,
Can you please rebase this PR.

**Pull request merged**
