### PR TITLE
Update to Golang 1.18.4

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
This PR updates the used Golang version to `1.18.4`.

**Release note**:

```other operator
Etcd-Druid's Golang version has been update to `1.18.4.`.
```

### CODE REVIEW

**Review by aaronfern — COMMENTED** [review]
Don't we also need to update the go version specified in `go.mod`?

**Comment by timuthy** [comment]
> Don't we also need to update the go version specified in `go.mod`?

That's a good point. It's not a must and I thought that I don't want to enforce developers to have Golang 1.18 on their machines to compile this project locally, as long as 1.17 is still supported.

**Comment by aaronfern** [comment]
Fair enough. Although can you please open an issue about the go version in `go.mod` so that we don't forget about it?

**Review by aaronfern — APPROVED** [review]
/lgtm

**Pull request merged**
