### PR TITLE
upgraded golang version to 1.22.1

### LINKED ISSUE #778: Upgrade golang version to 1.22
** What you would like to be added:**
Upgrade golang version to 1.22.1

**Motivation (Why is this needed?):**
Use language improvements that have been introduced in 1.22. Also the https://github.com/gardener/etcd-druid/pull/777 depends upon this version. [gardener](https://github.com/gardener/gardener/blob/master/go.mod) has already moved to 1.22.1.

### PR DESCRIPTION
**Pull request by unmarshall**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Upgrades golang version to 1.22.1

**Which issue(s) this PR fixes**:
Fixes #778 

**Special notes for your reviewer**:

**Release note**:

```noteworthy developer
Etcd-druid now uses golang 1.22.1.
```

### CODE REVIEW

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Comment by renormalize** [comment]
Wouldn't #777 achieve the same? Is there a reason for another PR?

**Comment by shreyas-s-rao** [comment]
@renormalize the concourse pipeline is built using the configuration from master branch, which can be found [here](https://github.com/gardener/etcd-druid/blob/master/.ci/pipeline_definitions). The tests for the PR branch run with this configuration, rather than the configuration from the PR branch itself. That's a current limitation of the concourse pipeline. So in order to ru go 1.22 tests in the PR, the master branch first needs to be updated with this change, after which the PR test pipeline will use this new configuration.

**Comment by renormalize** [comment]
Thanks for the explanation @shreyas-s-rao!

**Pull request closed without merging**
