### PR TITLE
Add support for overriding storage API endpoint for GCS

### LINKED ISSUE #736: [Feature] Consume GCS regional endpoints feature from etcd-backup-restore
**Feature (What you would like to be added):**
Consume [GCS regional endpoints](https://cloud.google.com/storage/docs/regional-endpoints) feature from etcd-backup-restore, added via https://github.com/gardener/etcd-backup-restore/issues/690.

/area backup
/platform gcp

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**How to categorize this PR?**

/area backup
/kind enhancement
/platform gcp

**What this PR does / why we need it**:
Add support for overriding storage API endpoint for Google GCS provider. This allows users to specify their own storage API [endpoint override](https://pkg.go.dev/cloud.google.com/go#hdr-Endpoint_Override), such as a [regional endpoint](https://cloud.google.com/storage/docs/regional-endpoints), or even a local GCS emulator endpoint. Users need to add a new field `storageAPIEndpoint` in their GCS backup secret, with the value in the format `http[s]://host[:port]/storage/v1/`, to utilise this feature.

Additionally, clean up some of the code and reduce duplicate code:
- combine `controllers/compaction.getCompactionJobEnvVar()` and `pkg/component/etcd/statefulset.getBackupRestoreEnvVars()` into `pkg/utils.GetBackupRestoreContainerEnvVars()` under `pkg/utils/envvar.go`, along with associated helper functions
- rename env var constants from `pkg/common/constants.go` to the format `Env*` with correct camel casing, and use in `pkg/utils.GetBackupRestoreContainerEnvVars()`

**Which issue(s) this PR fixes**:
Fixes #736 

**Special notes for your reviewer**:
/cc @dguendisch @anveshreddy18 
/invite @ishan16696 @seshachalam-yv 

**Release note**:

```feature user
Add support for overriding storage API endpoint for provider GCS, by adding new field `storageAPIEndpoint` in the GCP/GCS backup secret, with the value in the format `http[s]://host[:port]/storage/v1/`. ⚠️ Note: GCS storage API endpoint will not be overridden for `EtcdCopyBackupsTask`s, since backup buckets may reside in different regions.
```

### CODE REVIEW

**Review by seshachalam-yv — APPROVED** [review]
Thanks @shreyas-s-rao for introducing new constants for env vars.

Overall looks good to me.
Nice PR ❤️  
/lgtm

**Review by ishan16696 — APPROVED** [review]

**Pull request merged**
