### PR TITLE
Remove operation annotation before reconciling etcd resource

### LINKED ISSUE #204: [BUG] Remove operation annotation before reconciling etcd, in accordance to the gardener extension contract
**Describe the bug:**
The etcd controller removes the operation annotation from the `Etcd` resource *after* reconciling it, which goes against the [gardener extension contract](https://github.com/gardener/gardener/blob/master/docs/extensions/reconcile-trigger.md).

**Expected behavior:**
The etcd controller should remove the operation annotation from the `Etcd` resource before reconciling it [here](https://github.com/gardener/etcd-druid/blob/787692e268fcf2368113d34426ae9f1cc05bd29a/controllers/etcd_controller.go#L245).

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
Signed-off-by: Shreyas Rao <shreyas.sriganesh.rao@sap.com>

**How to categorize this PR?**

/area control-plane
/kind bug
/component etcd-druid

**What this PR does / why we need it**:
The etcd controller now removes the operation annotation from the `Etcd` resource *before* reconciling it, according to the [gardener extension contract](https://github.com/gardener/gardener/blob/master/docs/extensions/reconcile-trigger.md).

**Which issue(s) this PR fixes**:
Fixes #204 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
The operation annotation is now removed *before* reconciling the `Etcd` resource.
```

### CODE REVIEW

**Review by timuthy — APPROVED** [review]
/lgtm

**Review by amshuman-kr — COMMENTED** [review]
@shreyas-s-rao The changes look good. Can you please rebase?

**Review by amshuman-kr — APPROVED** [review]
Thanks for the rebase, @shreyas-s-rao! LGTM

**Pull request merged**
