### PR TITLE
Compaction job shouldn't add cluster-autoscaler.kubernetes.io/safe-to-evict: "false" annotation to compaction pod.

### PR DESCRIPTION
**Pull request by ishan16696**
/area cost
/kind enhancement

**What this PR does / why we need it**:
Right now, compaction job adds all annotation(s) present in `etcd custom resource spec` to compaction pod template. With this PR, compaction will not add annotation: `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"` to compaction pod if its present to improve node utilization.

**Which issue(s) this PR fixes**:
Please refer here: https://github.com/gardener/etcd-druid/issues/766#issuecomment-2084895795

**Special notes for your reviewer**:
This is the back-port for this PR: https://github.com/gardener/etcd-druid/pull/845 on branch `hotfix-v0.22`

**Release note**:

```noteworthy operator|user
To improve node utilization compaction job will not add annotation: `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"` to compaction pod.
```

### CODE REVIEW

**Comment by ishan16696** [comment]
I have run the druid e2e tests locally, they are passing. May be it just a flaky tests.
/retest

**Review by renormalize — APPROVED** [review]

**Review by anveshreddy18 — APPROVED** [review]

**Pull request merged**
