### PR TITLE
Upgrade dependency on `github.com/gardener/etcd-backup-restore` to `v0.31.0`.

### PR DESCRIPTION
**Pull request by renormalize**
**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:

* Upgrade the `etcdbrctl` dependency in `internal/images/images.yaml` to use `europe-docker.pkg.dev/gardener-project/public/gardener/etcdbrctl:v0.31.0`.

* Upgrade dependency on `github.com/gardener/etcd-backup-restore` to `v0.31.0` in `go.mod`.

* Upgrade indirect dependencies.

* Adapt `test/e2e/utils.go` to use the newer `List` API of `SnapStore` in `etcd-backup-restore`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```noteworthy developer
Upgraded `github.com/gardener/etcd-backup-restore` dependency from `0.29.0` to `0.31.0`.
```

```noteworthy operator
Upgraded `etcd-backup-restore` image version to `v0.31.0`.
```

```improvement operator github.com/gardener/etcd-backup-restore #753 @anveshreddy18
Improves the `renewTime` of full snapshot lease when the lease is updated as part of retry mechanism
```

```other operator github.com/gardener/etcd-backup-restore #793 @Shreyas-s14
Improved error handling in deletion of delta snapshots during snapshot garbage collection.
```

```improvement developer github.com/gardener/etcd-backup-restore #795 @renormalize
`etcd-backup-restore` now uses the `Restore` API exposed by `go.etcd.io/etcd/clientv3/snapshot` to perform restoration of the etcd data directory, moving away from performing restoration of the data directory manually.
```

```improvement user github.com/gardener/etcd-backup-restore #795 @renormalize
`etcd-backup-restore` now uses etcd version `v3.4.34` for the embedded etcd during restoration.
```

```improvement developer github.com/gardener/etcd-backup-restore #796 @renormalize
Standardize the `yaml` dependency to `sigs.k8s.io/yaml`. Replace deprecated `k8s.io/utils/pointer` with `k8s.io/utils/ptr`. Bump all direct dependencies to newer versions.
```

```improvement developer github.com/gardener/etcd-backup-restore #780 @renormalize
Builds for non-native platforms can now be done using the `docker-build` make target instead of having to invoke the `docker buildx` command. The platform can be specified using the `PLATFORM` variable which is passed while invoking make.
```

```improvement developer github.com/gardener/etcd-backup-restore #786 @renormalize
Upgrade the Go dependency to `go1.23.2`.
```

```improvement developer github.com/gardener/etcd-backup-restore #751 @renormalize
Azure Blob Storage client Go module upgraded to github.com/Azure/azure-sdk-for-go/sdk/storage/azblob from the deprecated github.com/Azure/azure-storage-blob-go
```

### CODE REVIEW

**Review by anveshreddy18 — APPROVED** [review]
Thanks for the upgrade and neat release notes. 🚀 
LGTM!

**Review by seshachalam-yv — APPROVED** [review]

**Pull request merged**
