### PR TITLE
Add Druid e2e tests for multi node etcd

### PR DESCRIPTION
**Pull request by seshachalam-yv**
**How to categorize this PR?**

/area testing
/kind enhancement

**What this PR does / why we need it**:
This PR adds  e2e tests for multi-node etcd

 **Etcd cluster operations:**

- [x] Creation of 3-member etcd cluster
- [x] Hibernation
    -  [x] Scale down from 3->0
    - [x] Scale up from 0->3
- [ ] Quorum is lost
- [ ] Single node is restored
- [ ] Zero downtime rolling updates  ---> **skipped** (`need to investigate why etcd cluster is not healthy while rolling update`)
- [x] Zero downtime maintenance operations - Defragmentation
- [x] Deletion of 3-member etcd cluster

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This PR made changes on top of https://github.com/gardener/etcd-druid/pull/296.
Introduced multi-node e2e tests and helper functions in following files

- [test/e2e/multi_node_etcd_test.go](https://github.com/seshachalam-yv/etcd-druid/blob/e2e-multi-node-etcd/test/e2e/multi_node_etcd_test.go)
- [test/e2e/utils.go](https://github.com/seshachalam-yv/etcd-druid/blob/e2e-multi-node-etcd/test/e2e/utils.go)

**Depends on the following issues/PRs**:
https://github.com/gardener/etcd-druid/pull/296

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @seshachalam-yv for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by timuthy** [comment]
Thanks for the PR and effort @seshachalam-yv. Since https://github.com/gardener/etcd-druid/pull/296 has been merged, can you please rebase this PR and adapt to the latest structural changes introduced in `test/e2e/etcd_backup_test.go`?

**Comment by seshachalam-yv** [comment]
Closed this PR, opened another PR to track this https://github.com/gardener/etcd-druid/pull/418

**Pull request closed without merging**
