### PR TITLE
Allow specifying labels for the etcd client Service

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Similar to https://github.com/gardener/etcd-druid/pull/438. In the context of https://github.com/gardener/gardener/issues/6718 I need to specify etcd client Service labels as well. The background is that  there is a new mutating webhook for EndpointSlices and the webhooks expect a well known `consider` label to select the given objects. Service labels are also mirrored to the corresponding EndpointSlice labels.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6718

**Release note**:

```other operator
The Etcd resource now allows specify etcd client Service labels via the `spec.etcd.clientService.labels` field.
```

### CODE REVIEW

**Review by shreyas-s-rao — APPROVED** [review]
@ialidzhikov Thanks for your PR.
/lgtm
/needs rebase

**Comment by ishan16696** [comment]
@ialidzhikov do you want another patch release of druid `v0.15.x` with this PR ?

**Comment by ialidzhikov** [comment]
Yes, that would be great. Thank you! Once this PR is merged to the master branch, I will take care to open the cherry-pick.

**Review by ishan16696 — APPROVED** [review]

**Pull request merged**
