### PR TITLE
Updated structure & frontmatter

### PR DESCRIPTION
**Pull request by n-boshnakov**
**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR updates the structure of etcd in the [public website](https://gardener.cloud/docs/other-components/etcd-druid/) and formats the titles of certain topics in the frontmatter.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Review by unmarshall — APPROVED** [review]
/lgtm

**Comment by unmarshall** [comment]
@shreyas-s-rao  please have a look as well

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Comment by shreyas-s-rao** [comment]
@n-boshnakov since this PR overrides #576 , that one can be closed in favour of this PR right?

**Pull request merged**
