### PR TITLE
Introduce persona-based docs

### PR DESCRIPTION
**Pull request by vlerenc**
**What this PR does / why we need it**:
We would like to introduce persona-based docs focussing on the already known release notes personas:
- users
- operators
- developers

**Special notes for your reviewer**:
@n-boshnakov Can you please share your thoughts?
@shreyas-s-rao We agreed not to change too much (maybe anything), but I thought, maybe we can prepare some basics already, so that you have a better starting point later. Anyway, please check whether the small change is OK for you. Thanks in advance.

**Release note**:
None as ~30 PRs have/will be opened and the message would be the same everywhere.

### CODE REVIEW

**Comment by n-boshnakov** [comment]
If we have decided to make changes solely in the manifest, then the `_index.md` files should also be removed from the folders, similarly to the [machine-controller-manager PR](https://github.com/gardener/machine-controller-manager/pull/836/files).

**Comment by vlerenc** [comment]
Thanks @n-boshnakov, good catch. I removed those (`_index.md`) and also the proposals (like with `gardener/gardener`), which incidentally also had an `_index.md` (not anymore).

Is that OK for the etcd druid maintainers?

**Comment by vlerenc** [comment]
Can this PR be merged (cc @shreyas-s-rao)? The failed tests look unrelated, are they?

**Comment by ishan16696** [comment]
> The failed tests look unrelated, are they?

yes, it is unrelated
/test pull-etcd-druid-e2e-kind

**Review by aaronfern — APPROVED** [review]

**Review by ishan16696 — APPROVED** [review]

**Review by shreyas-s-rao — APPROVED** [review]
@vlerenc thanks for taking the time to restructure the docs section.
/lgtm

**Pull request merged**
