### PR TITLE
Added etcd-druid-api content

### LINKED ISSUE #561: [Enhancement] Include Etcd Druid API as part of public documentation
**Feature (What you would like to be added):**
Right now https://gardener.cloud/docs/other-components/etcd-druid/ only has some details about the etcd and no details on the APIs that it exposes (CRDs).
Change the .docforge/manifest.yaml to include the API documentation that is now generated at https://github.com/gardener/etcd-druid-api/blob/main/docs/api-reference/druid.md

**Motivation (Why is this needed?):**
APIs are essential for community consumption

### PR DESCRIPTION
**Pull request by n-boshnakov**
**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR adds the contents of the [etcd-druid-api documentation](https://github.com/gardener/etcd-druid-api/tree/main/docs/api-reference) to the [etcd section](https://gardener.cloud/docs/other-components/etcd-druid/) of the public Gardener website.

**Which issue(s) this PR fixes**:
Fixes #561 

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Review by unmarshall — APPROVED** [review]
/lgtm

**Review by seshachalam-yv — APPROVED** [review]
/lgtm

**Pull request merged**
