### PR TITLE
Removed alias

### PR DESCRIPTION
**Pull request by n-boshnakov**
**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR removes an alias that was overriding (and breaking) the alias to the gardener api reference

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Review by JordanJordanov — APPROVED** [review]
/lgtm

**Comment by n-boshnakov** [comment]
@unmarshall Hello, would you be able to take a look at this PR?

**Review by unmarshall — APPROVED** [review]
/lgtm

**Comment by unmarshall** [comment]
@shreyas-s-rao have a quick look and then we can merge this PR

**Comment by n-boshnakov** [comment]
Closing this PR, since the changes in it are made in #605

**Pull request closed without merging**
