### PR TITLE
Custodian controller improvements

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area robustness
/kind enhancement

**What this PR does / why we need it**:
This PR improves several aspects of the custodian and etcd controllers as a preparation for #151:
- Adds a separate worker count flag for the custodian controller
- Controllers now make use of the Controller-Runtime provided logger instead of instantiating another instance via `logrus`
- Improves event triggers for the custodian controller, i.e., reconciliation happens on `create/update/delete` events for `etcd` and `create/delete` events for `statefulset`, as well as `status update` for `statefulsets`. Additionally, a mapper has been introduced which maps the `statefulset` for which an event was triggered to the corresponding `etcd` resource. Earlier, this has only worked because in most of the cases `etcd` and `statefulset` have the same `namespace/name`. 
- Custodian controller does not try to claim a `statefulset` anymore, since this is the job of the `etcd controller`.
- The `statefulset` condition sync has been removed as I didn't find any `statefulsets` which `conditions` in our system and further more, we should not try to sync and information from `statefulset.status` to `etcd` by default. If a `statusfulset.status.condition` is really of interest, then it can be read directly from the `statefulset`.

I created dedicated commits to simply the review.

**Which issue(s) this PR fixes**:
Fixes parts of #151

**Special notes for your reviewer**:
Previously, the custodian controller was setup by the following instruction:
`builder.For(&appsv1.StatefulSet{}).Owns(&druidv1alpha1.Etcd{})`

This caused event triggers for **all** `statefulset`s ([ref](https://github.com/kubernetes-sigs/controller-runtime/blob/72fc2c61d2b34cfee62910d22ae7546f46b1893c/pkg/builder/controller.go#L228)) (-> we don't need to enqueue for events of all `statefulset`s in the cluster) **and** `etcd`s with an `ownerReference` ([ref](https://github.com/kubernetes-sigs/controller-runtime/blob/72fc2c61d2b34cfee62910d22ae7546f46b1893c/pkg/builder/controller.go#L234)) (-> `etcd`s don't have an owner reference).

**Release note**:

```feature operator
It is now possible to configure the count of custodian controller workers by `--custodian-workers`.
```
```other operator
The reconciliation loop count of the custodian controller has been improved. Now, reconciliation only happens at relevant `create/update/delete` events.
```

### CODE REVIEW

**Review by amshuman-kr — APPROVED** [review]
Thanks a lot for the changes and some much needed corrections! Not the least, the long-pending use of `gomock` ❤️ 

/lgtm

**Comment by amshuman-kr** [comment]
@abdasgupta Can you please give your comments? Based on that I will merge.

**Comment by abdasgupta** [comment]
I have went through the PR. I am fine with the changes. I also tested it in local cluster. It works as it should. Thanks @timuthy for your PR.

**Review by abdasgupta — APPROVED** [review]
LGTM

**Pull request merged**
