### PR TITLE
Bump github.com/gardener/gardener from `1.65.0` to `1.76.0`

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
This PR bumps the gardener version to `v1.76.0`, and drops the unneeded dependency of `k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a+incompatible`.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6807

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by aaronfern** [comment]
I see that you've done quite a bit more as part of this PR such as `removing dead code` and `dropping support for PDB v1.21`
Unless it is essential to vendoring gardener 1.76, please remove them from this PR and raise more PRs if necessary

**Comment by acumino** [comment]
> I see that you've done quite a bit more as part of this PR such as `removing dead code` and `dropping support for PDB v1.21` Unless it is essential to vendoring gardener 1.76, please remove them from this PR and raise more PRs if necessary

Gardener now doesn't support cluster <=1.21 [ref](https://github.com/gardener/gardener/issues/7405). As part of that cleanup is done here for PDBs.

For `removing dead code`, isn't it always good to remove redundant code, why do we want to keep it in the repo if it's not needed?

**Comment by unmarshall** [comment]
>For removing dead code, isn't it always good to remove redundant code, why do we want to keep it in the repo if it's not needed?

Removal of dead code is always welcome but then either change the scope of the PR or file a separate PR.

**Comment by aaronfern** [comment]
> Gardener now doesn't support cluster <=1.21 https://github.com/gardener/gardener/issues/7405. As part of that cleanup is done here for PDBs
etcd-druid can be used stand alone as well and gardener is not the sole consumer. If we drop support for PDB v1beta1, then we'd need a release note as it's a breaking change. A separate PR would also help us track this change in the future

> For removing dead code, isn't it always good to remove redundant code, why do we want to keep it in the repo if it's not needed?
You misunderstand me. I do not want to keep this "dead" code. It was some leftover code that ideally should've been removed while moving all our objects to the component model. A separate PR for this was meant so that it's tracked


All I'm saying is that I do not like that this PR went way over it's scope and it's gets difficult for us to track it in the future :)

**Comment by aaronfern** [comment]
@acumino e2e tests are failing and at first glance it seems like it's due to the grpc package that was upgraded. Can you please take a look?

**Comment by acumino** [comment]
> @acumino e2e tests are failing and at first glance it seems like it's due to the grpc package that was upgraded. Can you please take a look?

Pinned version of the upgraded dependency in https://github.com/gardener/etcd-druid/pull/657/commits/a7cbb664a26fdc9bfdbb0c379f908c3ce771ba10. These can be removed when `grpc` is upgraded.

**Comment by acumino** [comment]
/hold cancel
Addressed all the concerns.

**Comment by aaronfern** [comment]
Thanks for the PR! Changes looks good to me
Please rebase onto latest master and I think we're good to go

**Review by seshachalam-yv — APPROVED** [review]
Thanks @acumino
/lgtm

**Pull request merged**
