### PR TITLE
Exclude outdated client-go in `go.mod`

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
This PR excludes outdated client-go in `go.mod`.  This is the first step to removing the cyclic dependency of `k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible`

/invite @ialidzhikov 

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6807

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by seshachalam-yv — COMMENTED** [review]
/lgtm

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Pull request merged**
