### PR TITLE
Fix test failures with bootstrap script change

### LINKED ISSUE #160: [BUG] Fix failing test after
**Describe the bug:**
The following test case is failing after the commit https://github.com/gardener/etcd-druid/commit/72ec7a0d5d5b1a25dbacd0546897bf8239630755. 

**Expected behavior:**
No test cases should fail.

**How To Reproduce (as minimally and precisely as possible):**

Run `make test` on the commit https://github.com/gardener/etcd-druid/commit/72ec7a0d5d5b1a25dbacd0546897bf8239630755.

**Logs:**

```
• Failure [6.027 seconds]
Druid when etcd resource is created [It] if fields are set in etcd.Spec and TLS enabled, the resources should reflect the spec changes 
/tmp/build/a94a8fe5/pull-request-gardener.etcd-druid-pr.master/tmp/src/github.com/gardener/etcd-druid/controllers/etcd_controller_test.go:482

  Expected
      <string>: ConfigMap
  to match fields: {
  .Data."bootstrap.sh":
  	Expected
  	    <string>: "...tus = '143'..."
  	to equal               |
  	    <string>: "...tus == '143..."
  }
  

  /tmp/build/a94a8fe5/pull-request-gardener.etcd-druid-pr.master/tmp/src/github.com/gardener/etcd-druid/controllers/etcd_controller_test.go:882
```

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**How to categorize this PR?**

/area backup
/kind bug
/priority blocker

**What this PR does / why we need it**:
Fix test failure from bootstrap script fix

**Which issue(s) this PR fixes**:
Fixes #160 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by amshuman-kr** [comment]
Thanks for the change @shreyas-s-rao!

But the build still -> fails https://concourse.ci.gardener.cloud/builds/7036984#L6071d8e7:62:77

**Comment by shreyas-s-rao** [comment]
@amshuman-kr Yes, overlooked that. I've fixed it and tested it now. Tests should have passed now. Sorry for the confusion.

**Review by amshuman-kr — APPROVED** [review]
Thanks for the changes @shreyas-s-rao. LGTM

**Comment by shreyas-s-rao** [comment]
@amshuman-kr can you please merge the PR in that case? Thanks

**Pull request merged**
