### PR TITLE
Simplify reconciliation

### LINKED ISSUE #186: [Feature] Simplify reconciliation by simplifying claim logic for StatefulSet, Service and ConfigMap based on Etcd resource name
**Feature (What you would like to be added):**

The reconciliation flow of `etcd-druid` includes claiming from potentially multiple pre-existing `StatefulSet`, `Service` and `ConfigMap` objects if they exist. This is done by [selecting the objects based on `spec.selector` in the `Etcd` resource](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/controller_ref_manager.go#L192), [claiming one of the matching objects (if any)](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/controller_ref_manager.go#L82-L153) and [deleting the rest of the objects (if any)](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/etcd_controller.go#L600). If no matching objects are found then a [new object is created](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/etcd_controller.go#L646).

The logic of claiming from multiple pre-existing objects objects based on`spec.selector` was done because of the following reasons.
1. Migration from the time before `etcd-druid` was introduced. I.e. adopting objects created from the time before `etcd-druid` was introduced minimised and simplified clean up.
2. Keeping options open before multi-node ETCD design was finalised to use a [single `StatefulSet` for all the members of an ETCD cluster](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/multi-node/README.md#kubernetes-context). Another alternative of using [one `StatefulSet` for each member of an ETCD cluster](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/multi-node/README.md#alternative-1) was still open at that time.

Now that the migration scenario as well as the multi-node design don't need the functionality of claiming from multiple pre-existing objects, we can simplify the claim logic to just pick the object to be claimed by the same name as the `Etcd` resource . We will still need the [claim functionality](https://github.com/gardener/etcd-druid/blob/6030a7e67d726a665db690380fa2fa81adae3822/controllers/controller_ref_manager.go#L82-L153) to mark it as claimed, of course.

**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**

### PR DESCRIPTION
**Pull request by amshuman-kr**
**How to categorize this PR?**

/area control-plane
/kind technical-debt

**What this PR does / why we need it**:

Simplified claim logic in reconciliation by replacing selecting existing objects based on a selector with `CreateOrUpdate` or recreating them if necessary.

**Which issue(s) this PR fixes**:
Fixes #186 

**Special notes for your reviewer**:
This PR is based on #203 and ensures that all the test cases as of #203 are still working after the simplification. So, only the commits https://github.com/gardener/etcd-druid/commit/67df3c125fc0518c0f9274cb44960c217c599617 and https://github.com/gardener/etcd-druid/commit/36a8ed60695e286b850149aa9cc9bbfa6bda78a5 are relevant in this PR.

This PR should be merged only after rebasing after #203 is merged.

**Release note**:

```other operator
Simplified claim logic in reconciliation by replacing selecting existing objects based on a selector with `CreateOrUpdate` or recreating them if necessary.
```

### CODE REVIEW

**Comment by amshuman-kr** [comment]
[Rebased](https://github.com/gardener/etcd-druid/pull/208#event-5198747380) on #203 again because it was also rebased.

**Comment by amshuman-kr** [comment]
[Resolved conflicts](https://github.com/gardener/etcd-druid/compare/01dd86cbf81ecd7bb8be33099998525611e1567f..36a8ed60695e286b850149aa9cc9bbfa6bda78a5) and adapted test cases for #222 and [rebased](https://github.com/gardener/etcd-druid/pull/208#event-5233281770) after [v0.6.0](https://github.com/gardener/etcd-druid/releases/tag/v0.6.0) release.

**Review by abdasgupta — COMMENTED** [review]
Thanks for the PR. Greatly simplified. I think, we can remove all cron job related logics in this PR. What say?

**Comment by timuthy** [comment]
/close
We will gradually move to component handling as done in https://github.com/gardener/etcd-druid/pull/262 and simplify the reconciliation (i.e. drop claiming logic) along the way. (/cc @abdasgupta @shreyas-s-rao @aaronfern @ishan16696)

**Pull request closed without merging**
