### PR TITLE
Update to Golang 1.18.5

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
This PR updates the Golang version to 1.18.5.

**Release note**:

```other operator
The Golang version used to compile Etcd-Druid has been updated to `go 1.18.5`.
```

### CODE REVIEW

**Comment by timuthy** [comment]
/ping @aaronfern @ishan16696 @abdasgupta 
Can one of you please review?

**Comment by ishan16696** [comment]
Thanks for PR @timuthy ,
Is there a reason why [go.mod](https://github.com/gardener/etcd-druid/blob/master/go.mod#L3) is not been updated ?

**Comment by timuthy** [comment]
> Is there a reason why [go.mod](https://github.com/gardener/etcd-druid/blob/master/go.mod#L3) is not been updated ?

The reason was earlier that we didn't need any 1.18 features and we wanted to allow a compilation with 1.17 as well. I now also updated it, good idea 👍 PTAL.

**Review by aaronfern — APPROVED** [review]
/lgtm

**Review by ishan16696 — APPROVED** [review]

**Pull request merged**
