### PR TITLE
Revert "Enable TLS for backup-restore server"

### PR DESCRIPTION
**Pull request by georgekuruvillak**
Reverts gardener/etcd-druid#16

### CODE REVIEW

**Comment by shreyas-s-rao** [comment]
/close
In favour of https://github.com/gardener/etcd-druid/pull/22

**Comment by shreyas-s-rao** [comment]
Sure @amshuman-kr, go ahead. I don't have maintainer access on the repo

**Comment by georgekuruvillak** [comment]
In favour of #22

**Pull request closed without merging**
