### PR TITLE
Maintain project dependencies and images

### PR DESCRIPTION
**Pull request by timuthy**
**What this PR does / why we need it**:
This PR updates dependency of the druid component.

Along the way, it improves several things:
- [Gardener's check script](https://github.com/gardener/gardener/blob/master/hack/check.sh) is now executed as part of `make check` in favor of `go vet` only (Make target `vet` has been dropped)
- `make revendor` now updates `.github` templates from `gardener/gardener`
- Several golang-ci findings have been resolved
- The `controller-gen` from the `vendor` directory is now considered to generate assets in order to generate a stable output
- Curl has been removed from the Druid image for security reasons
- New leader election options have been added to eventually migrate to `lease.coordination.k8s.io` based leader election in the future (/cc @timebertt)

⚠️ PR #139 must be merged first!

/cc @shreyas-s-rao @amshuman-kr 

I split the PR into different commits to make reviewing easier. HTH.

**Release note**:

```improvement developer
Several Go and image dependencies have been updated.
```
```improvement developer
- [Gardener's check script](https://github.com/gardener/gardener/blob/master/hack/check.sh) is now executed as part of `make check` in favor of `go vet` only (Make target `vet` has been dropped)
- `make revendor` now updates `.github` templates from `gardener/gardener`
- Several golang-ci findings have been resolved
- The `controller-gen` from the `vendor` directory is now considered to generate assets in order to get a stable output.
```
```action operator
etcd-druid images won't be delivered with `curl` anymore.
```
```action operator
etcd-druid now needs CRUD permissions for `leaese.coordination.k8s.io` object in order to perform leader election.
```

### CODE REVIEW

**Comment by timuthy** [comment]
ping @gardener/etcd-druid-maintainers

**Comment by amshuman-kr** [comment]
Sorry for the delay, @timuthy. I have merged #139. But now this PR has a conflict because I think it has a commit in common with #139. Can you please rebase?

I probably will request you to rebase #146  after this PR is merged because there are common commits there too.

**Comment by timuthy** [comment]
Thanks @amshuman-kr. I've resolved the merge conflicts and will continue with #146 once this PR is merged.

**Comment by amshuman-kr** [comment]
> Thanks @amshuman-kr. I've resolved the merge conflicts and will continue with #146 once this PR is merged.

Thanks @timuthy! I will try to merge this using rebase instead of merge. Hope that avoids one more rebase for you.

**Review by amshuman-kr — APPROVED** [review]

**Pull request merged**
