### PR TITLE
upgraded go version to 1.22.1

### LINKED ISSUE #778: Upgrade golang version to 1.22
** What you would like to be added:**
Upgrade golang version to 1.22.1

**Motivation (Why is this needed?):**
Use language improvements that have been introduced in 1.22. Also the https://github.com/gardener/etcd-druid/pull/777 depends upon this version. [gardener](https://github.com/gardener/gardener/blob/master/go.mod) has already moved to 1.22.1.

### PR DESCRIPTION
**Pull request by unmarshall**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Upgrades golang version to 1.22.1

**Which issue(s) this PR fixes**:
Fixes #778 

**Special notes for your reviewer**:

**Release note**:

```other operator
etcd-druid now uses golang version 1.22.1
```

### CODE REVIEW

**Comment by unmarshall** [comment]
All unit tests passed locally
```
go build -o hack/tools/bin/ginkgo github.com/onsi/ginkgo/v2/ginkgo
go build -o hack/tools/bin/setup-envtest sigs.k8s.io/controller-runtime/tools/setup-envtest
> Installing envtest tools@1.22 with setup-envtest if necessary
using envtest tools installed at '/Users/i062009/Library/Application Support/io.kubebuilder.envtest/k8s/1.22.1-darwin-amd64'
> Tests
[1712121732] Condition Suite - 19/19 specs ••••••••••••••••••• SUCCESS! 2.201625ms PASS
[1712121732] RoleBinding Component Suite - 7/7 specs ••••••• SUCCESS! 1.283ms PASS
[1712121732] Configmap Component Suite - 4/4 specs •••• SUCCESS! 2.05225ms PASS
[1712121732] Controller Utils suite - 8/8 specs •••••••• SUCCESS! 505.792µs PASS
[1712121732] Utils Suite - 19/19 specs ••••••••••••••••••• SUCCESS! 3.367958ms PASS
[1712121732] Metrics Suite - 4/4 specs •••• SUCCESS! 310.542µs PASS
[1712121732] Mapper Suite - 6/6 specs •••••• SUCCESS! 929.708µs PASS
[1712121732] Etcd Controller Suite - 0/0 specs  SUCCESS! 93.916µs PASS
[1712121732] EtcdCopyBackupsTask Controller Suite - 59/59 specs ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 6.546209ms PASS
[1712121732] Secret Controller Suite - 10/10 specs •••••••••• SUCCESS! 1.539208ms PASS
[1712121732] Predicate Suite - 25/25 specs ••••••••••••••••••••••••• SUCCESS! 1.950375ms PASS
[1712121732] Service Component Suite - 10/10 specs •••••••••• SUCCESS! 2.351333ms PASS
[1712121732] PodDisruptionBudget Component Suite - 8/8 specs •••••••• SUCCESS! 4.425583ms PASS
[1712121732] ServiceAccount Component Suite - 8/8 specs •••••••• SUCCESS! 1.234417ms PASS
[1712121732] Etcd Component Suite - 6/6 specs •••••• SUCCESS! 3.083542ms PASS
[1712121732] Status Suite - 1/1 specs • SUCCESS! 374.125µs PASS
[1712121732] Role Component Suite - 7/7 specs ••••••• SUCCESS! 1.662166ms PASS
[1712121732] Etcd Member Suite - 9/9 specs ••••••••• SUCCESS! 1.364541ms PASS
[1712121732] Statefulset Component Suite - 21/21 specs ••••••••••••••••••••• SUCCESS! 13.41475ms PASS
[1712121732] Etcd Validation Suite - 13/13 specs ••••••••••••• SUCCESS! 1.494625ms PASS
[1712121732] v1 Suite - 13/13 specs ••••••••••••• SUCCESS! 8.130741083s PASS
```

**Comment by unmarshall** [comment]
All integration-tests passed locally:
`make test-integration`
```
> Installing envtest tools@1.22 with setup-envtest if necessary
using envtest tools installed at '/Users/i062009/Library/Application Support/io.kubebuilder.envtest/k8s/1.22.1-darwin-amd64'
> Tests
[1712121797] Custodian Controller Suite - 4/4 specs •••• SUCCESS! 10.306124042s PASS
[1712121797] Secret Controller Suite - 1/1 specs • SUCCESS! 7.543844125s PASS
[1712121797] EtcdCopyBackupsTask Controller Suite - 8/8 specs •••••••• SUCCESS! 1m12.938228167s PASS
[1712121797] Compaction Controller Suite - 10/10 specs •••••••••• SUCCESS! 40.641160209s PASS
[1712121797] Etcd Controller Suite - 37/37 specs ••••••••••••••••••••••••••••••••••••• SUCCESS! 5m16.414722208s PASS

Ginkgo ran 5 suites in 7m35.347779375s
Test Suite Passed
```

**Comment by aaronfern** [comment]
Did you run `make revendor`? 
Just curious because I do not see any changes in `go.sum`

**Comment by unmarshall** [comment]
> Did you run `make revendor`? Just curious because I do not see any changes in `go.sum`

I did not run this specific target but i ran `go mod vendor` followed by `go mod tidy` which effectively does the same as the `revendor` target. You can pull this PR and check if you are facing any issues.

**Comment by unmarshall** [comment]
Ran e2e tests locally:

Run #1
There were a total of 3 failing tests:
```
Summarizing 3 Failures:
  [FAIL] Etcd when a single-node is configured [It] should scale a single-node etcd (TLS not enabled for peerUrl) to a multi-node etcd cluster (TLS enabled for peerUrl)
  /Users/i062009/src/github.com/unmarshall/etcd-druid/test/e2e/etcd_multi_node_test.go:390
  [FAIL] Etcd when a single-node is configured [It] should scale down a single-node etcd to 0 replica, then scale up from 0->1 replica and then from 1->3 replicas with TLS enabled for cluster peerUrl
  /Users/i062009/src/github.com/unmarshall/etcd-druid/test/e2e/etcd_multi_node_test.go:390
  [FAIL] Etcd Compaction when compaction is enabled for single-node etcd with provider aws [It] should test compaction on backup
  /Users/i062009/src/github.com/unmarshall/etcd-druid/test/e2e/etcd_compaction_test.go:151

Ran 7 of 7 Specs in 1782.468 seconds
FAIL! -- 4 Passed | 3 Failed | 0 Pending | 0 Skipped
```
Run #2
Second time i added `Focus` to multi-node tests and this time all focussed tests passed.
```
1. Etcd when a single-node is configured should scale a single-node etcd (TLS not enabled for peerUrl) to a multi-node etcd cluster (TLS not enabled for peerUrl)
2. Etcd when a single-node is configured should scale a single-node etcd (TLS not enabled for peerUrl) to a multi-node etcd cluster (TLS enabled for peerUrl)
3. Etcd when a single-node is configured should scale down a single-node etcd to 0, then scale up from 0->1 replicas and then from 1->3 replicas
4. Etcd when a single-node is configured should scale down a single-node etcd to 0 replica, then scale up from 0->1 replica and then from 1->3 replicas with TLS enabled for cluster peerUrl
```
So there seems to be some flakiness to the tests which we will have to investigate.

**Comment by shreyas-s-rao** [comment]
Reduced flakiness in downtime validator job based tests in e2e test suite.
```
-------------------
Running e2e tests
-------------------
=== RUN   TestIntegration
Running Suite: e2e Suite - /Users/i349079/go/src/github.com/gardener/etcd-druid/test/e2e
========================================================================================
Random Seed: 1712133003

Will run 1 of 7 specs
------------------------------
[BeforeSuite] 
/Users/i349079/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:62
  > Enter [BeforeSuite] TOP-LEVEL @ 04/03/24 14:00:03.236
  {"level":"info","ts":"2024-04-03T14:00:03+05:30","msg":"creating namespace","namespace":"shoot"}
  {"level":"info","ts":"2024-04-03T14:00:03+05:30","msg":"creating secret","secret":{"namespace":"shoot","name":"ca-etcd-aws"}}
  {"level":"info","ts":"2024-04-03T14:00:03+05:30","msg":"creating secret","secret":{"namespace":"shoot","name":"etcd-server-cert-aws"}}
  {"level":"info","ts":"2024-04-03T14:00:03+05:30","msg":"creating secret","secret":{"namespace":"shoot","name":"etcd-client-tls-aws"}}
  < Exit [BeforeSuite] TOP-LEVEL @ 04/03/24 14:00:03.346 (110ms)
[BeforeSuite] PASSED [0.113 seconds]
------------------------------
SS
------------------------------
Etcd when multi-node is configured should perform etcd operations
/Users/i349079/go/src/github.com/gardener/etcd-druid/test/e2e/etcd_multi_node_test.go:77
  > Enter [BeforeEach] Etcd @ 04/03/24 14:00:03.349
  {"level":"info","ts":"2024-04-03T14:00:03+05:30","msg":"creating secret","secret":{"namespace":"shoot","name":"etcd-backup-aws"}}
  < Exit [BeforeEach] Etcd @ 04/03/24 14:00:03.389 (39ms)
  > Enter [It] should perform etcd operations @ 04/03/24 14:00:03.389
  STEP: Create etcd @ 04/03/24 14:00:03.389
  {"level":"info","ts":"2024-04-03T14:00:03+05:30","msg":"Waiting for etcd to become ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:02:58+05:30","msg":"etcd is ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:02:58+05:30","msg":"Checking statefulset","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:02:58+05:30","msg":"Checking configmap","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:02:58+05:30","msg":"Checking client service","etcd-multi-node":"shoot/etcd-aws"}
  STEP: Hibernate etcd (Scale down from 3 replicas to 0) @ 04/03/24 14:02:58.724
  {"level":"info","ts":"2024-04-03T14:02:58+05:30","msg":"Waiting for statefulset spec to reflect change in replicas to 0","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:03:00+05:30","msg":"Checking etcd","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:03:02+05:30","msg":"Checking statefulset","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:03:02+05:30","msg":"etcd is hibernated","etcd-multi-node":"shoot/etcd-aws"}
  STEP: Wakeup etcd (Scale up from 0->3 replicas) @ 04/03/24 14:03:02.769
  {"level":"info","ts":"2024-04-03T14:05:09+05:30","msg":"Waiting for etcd to become ready"}
  {"level":"info","ts":"2024-04-03T14:05:19+05:30","msg":"etcd is ready"}
  {"level":"info","ts":"2024-04-03T14:05:19+05:30","msg":"Checking statefulset"}
  {"level":"info","ts":"2024-04-03T14:05:19+05:30","msg":"Checking configmap"}
  {"level":"info","ts":"2024-04-03T14:05:19+05:30","msg":"Checking client service"}
  STEP: Zero downtime rolling updates @ 04/03/24 14:05:19.712
  {"level":"info","ts":"2024-04-03T14:05:19+05:30","msg":"Creating job to ensure etcd zero downtime","job":"etcd-zero-down-time-validator-rolling-update"}
  {"level":"info","ts":"2024-04-03T14:05:35+05:30","msg":"Job is ready","job":"etcd-zero-down-time-validator-rolling-update"}
  {"level":"info","ts":"2024-04-03T14:06:42+05:30","msg":"Waiting for etcd to become ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:06:42+05:30","msg":"etcd is ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:06:42+05:30","msg":"Checking statefulset","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:06:42+05:30","msg":"Checking configmap","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:06:42+05:30","msg":"Checking client service","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:06:42+05:30","msg":"Etcd Cluster is healthy and there is no downtime","etcd-multi-node":"shoot/etcd-aws"}
  STEP: Zero downtime maintenance operation: defragmentation @ 04/03/24 14:06:42.156
  {"level":"info","ts":"2024-04-03T14:06:42+05:30","msg":"Configure defragmentation schedule for every 1 minute","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:07:48+05:30","msg":"Waiting for etcd to become ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:07:48+05:30","msg":"etcd is ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:07:48+05:30","msg":"Checking statefulset","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:07:48+05:30","msg":"Checking configmap","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:07:48+05:30","msg":"Checking client service","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:07:48+05:30","msg":"Etcd Cluster is healthy and there is no downtime","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:07:48+05:30","msg":"Waiting for defragmentation to finish","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:01+05:30","msg":"Defragmentation is finished","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:01+05:30","msg":"Checking any Etcd downtime","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:01+05:30","msg":"Etcd Cluster is healthy and there is no downtime","etcd-multi-node":"shoot/etcd-aws"}
  STEP: Member restart with data-dir/pvc intact @ 04/03/24 14:09:01.264
  {"level":"info","ts":"2024-04-03T14:09:01+05:30","msg":"Delete one member pod","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:01+05:30","msg":"waiting for sts to become unready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:03+05:30","msg":"sts is unready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:03+05:30","msg":"Waiting for etcd to become ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:17+05:30","msg":"etcd is ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:17+05:30","msg":"Checking statefulset","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:17+05:30","msg":"Checking configmap","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:17+05:30","msg":"Checking client service","etcd-multi-node":"shoot/etcd-aws"}
  STEP: Single member restoration @ 04/03/24 14:09:17.393
  {"level":"info","ts":"2024-04-03T14:09:17+05:30","msg":"Create debug pod","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:29+05:30","msg":"Delete member dir of one member pod","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:09:29+05:30","msg":"waiting for sts to become unready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:01+05:30","msg":"sts is unready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:01+05:30","msg":"Waiting for etcd to become ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:15+05:30","msg":"etcd is ready","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:15+05:30","msg":"Checking statefulset","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:15+05:30","msg":"Checking configmap","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:15+05:30","msg":"Checking client service","etcd-multi-node":"shoot/etcd-aws"}
  STEP: Delete debug pod @ 04/03/24 14:10:15.798
  STEP: Delete etcd @ 04/03/24 14:10:15.801
  {"level":"info","ts":"2024-04-03T14:10:15+05:30","msg":"Checking if etcd is gone","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:17+05:30","msg":"Checking if statefulset is gone","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:17+05:30","msg":"Checking if configmap is gone","etcd-multi-node":"shoot/etcd-aws"}
  {"level":"info","ts":"2024-04-03T14:10:17+05:30","msg":"Checking client service is gone","etcd-multi-node":"shoot/etcd-aws"}
  < Exit [It] should perform etcd operations @ 04/03/24 14:10:17.856 (10m14.466s)
  > Enter [AfterEach] Etcd @ 04/03/24 14:10:17.856
  < Exit [AfterEach] Etcd @ 04/03/24 14:10:17.859 (3ms)
• [614.508 seconds]
------------------------------
SSSS
------------------------------
[AfterSuite] 
/Users/i349079/go/src/github.com/gardener/etcd-druid/test/e2e/suite_test.go:98
  > Enter [AfterSuite] TOP-LEVEL @ 04/03/24 14:10:17.859
  {"level":"info","ts":"2024-04-03T14:10:17+05:30","msg":"deleting namespace","namespace":"shoot","namespace":"shoot"}
  < Exit [AfterSuite] TOP-LEVEL @ 04/03/24 14:10:49.991 (32.132s)
[AfterSuite] PASSED [32.132 seconds]
------------------------------

Ran 1 of 7 Specs in 646.754 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 6 Skipped
PASS | FOCUSED
```

**Comment by shreyas-s-rao** [comment]
Prow jobs for e2e tests are passing now. Seems to be some flakiness, which we will re-look at in another PR.
/invite @ishan16696 PTAL

**Comment by ishan16696** [comment]
> I  did not run this specific target but i ran go mod vendor followed by go mod tidy which effectively does the same as the revendor target. You can pull this PR and check if you are facing any issues

yes, I tried that ..it works fine

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Comment by ishan16696** [comment]
make check failed locally
```
go build -o hack/tools/bin/goimports golang.org/x/tools/cmd/goimports
go build -o hack/tools/bin/controller-gen sigs.k8s.io/controller-tools/cmd/controller-gen
Generating CRDs for druid.gardener.cloud group
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104c7cd94]

goroutine 6 [running]:
go/types.(*Checker).handleBailout(0x14000392000, 0x1400014fd18)
	/Users/I539698/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-arm64/src/go/types/check.go:367 +0x9c
panic({0x104f4d480?, 0x1054ebe40?})
	/Users/I539698/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-arm64/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x105017a70, 0x1054f4660})
	/Users/I539698/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-arm64/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
```

**Comment by unmarshall** [comment]
Another PR will be raised.

**Comment by shreyas-s-rao** [comment]
Superseded by #784

**Pull request closed without merging**
