### PR TITLE
Upgrade golang version to 1.22.2 and remove dependency on g/g scripts

### LINKED ISSUE #778: Upgrade golang version to 1.22
** What you would like to be added:**
Upgrade golang version to 1.22.1

**Motivation (Why is this needed?):**
Use language improvements that have been introduced in 1.22. Also the https://github.com/gardener/etcd-druid/pull/777 depends upon this version. [gardener](https://github.com/gardener/gardener/blob/master/go.mod) has already moved to 1.22.1.

### PR DESCRIPTION
**Pull request by unmarshall**
**How to categorize this PR?**

How to categorize this PR?

/area control-plane
/kind enhancement

What this PR does / why we need it:

- Upgrades golang version to 1.22.2
- Removes dependency on g/g `hack/scripts`
- Fixes some flakiness in e2e tests
- Replace `github.com/golang/mock` with `go.uber.org/mock`
- Upgrade golangci-lint and fix linting errors

Which issue(s) this PR fixes:
Fixes #778, #503

Special notes for your reviewer:

Release note:

```noteworthy developer
etcd-druid now uses golang version 1.22.2
`github.com/golang/mock` is replaced by `go.uber.org/mock` since the former is no longer maintained
upgraded golangci-lint to v1.57.2
simplified hack/scripts and removed dependency on g/g hack/scripts
```

### CODE REVIEW

**Comment by unmarshall** [comment]
- `make check` passes locally
- `make test` passes locally
- `make test-integration` passes locally
- `make ci-e2e-kind` passes locally

**Comment by renormalize** [comment]
Will this PR be closed, or will it be rebased on #748?

**Comment by unmarshall** [comment]
i will break this PR into 2: remove g/g scripts and then change go version. This PR will get closed in favor of new PRs.

**Pull request closed without merging**
