### PR TITLE
Hvpa-controller dependency update

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
Part of [#6807](https://github.com/gardener/gardener/issues/6807)
Main motivation is that `github.com/gardener/hvpa-controller` carries old `client-go` dependency version and `github.com/gardener/hvpa-controller/api` does not

1. Fix go mod command execution order in Makefile
2. Rebuilds the hvpa-controller dependency in `go.mod`

**Special notes for your reviewer**:
Steps done to achieve the result: 
1. Delete `github.com/gardener/hvpa-controller v0.3.1 // indirect` on row 48
2. run `make revendor` (use fixed version of `make revendor` proposed in this PR)

**Release note**:

```other dependency
Update HVPA dependency to `github.com/gardener/hvpa-controller/api:v0.5.0`.
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@gardener/etcd-druid-maintainers do you have any concerns wrt to this change? It is updating a transitive dependency (`github.com/gardener/hvpa-controller`) to reduce the number of dependencies that bring the broken version `k8s.io/client-go` - `v11.0.1-0.20190409021438-1a26190bd76a+incompatible`. We were not able to understand why in the first place the go tool picks `github.com/gardener/hvpa-controller@v0.3.1`. As described in the PR description, removing the indirect `github.com/gardener/hvpa-controller` dependency leads `github.com/gardener/hvpa-controller/api@v0.5.0` to be picked instead and `github.com/gardener/hvpa-controller/api@v0.5.0` does not bring the broken `k8s.io/client-go` version.

**Review by unmarshall — COMMENTED** [review]
Looks ok to me

**Review by aaronfern — APPROVED** [review]

**Comment by ialidzhikov** [comment]
@gardener/etcd-druid-maintainers is it possible to move forward with this change? Let us know if you have any concerns.

**Comment by shreyas-s-rao** [comment]
I have taken the liberty to change the release notes:
```
other dependency
Update HVPA dependency to `github.com/gardener/hvpa-controller/api:v0.5.0`.

bugfix developer
Fix `make revendor` target.

```

**Comment by ialidzhikov** [comment]
> @Kostov6 can you please rebase the PR on latest master so that we can merge it?

@shreyas-s-rao the PR is now rebased.

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Pull request merged**
