### PR TITLE
Block public access to S3 bucket as per standard compliance rules

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**How to categorize this PR?**

/area backup
/area security
/area compliance
/kind task
/kind test
/platform aws

**What this PR does / why we need it**:
This PR configures the S3 buckets created by e2e tests to be blocked from public access as per standard practices. This is achieved by putting a public-access-block on the created bucket, as per [AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-public-access-block.html).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc @vlerenc 

**Release note**:

```improvement developer
Block public access for S3 buckets created by e2e tests.
```

### CODE REVIEW

**Comment by shreyas-s-rao** [comment]
@abdasgupta I have addressed your comment https://github.com/gardener/etcd-backup-restore/pull/615#discussion_r1171165629 in this PR as well. Please confirm that I have not added the bucket policy for localstack S3 buckets since they are exposed on `http` endpoint instead of `https`, so setting this policy on such buckets will fail the localstack-based e2e tests

**Comment by abdasgupta** [comment]
It looks fine, can you verify if you can run `make ci-e2e-kind` following `docs/development/local-e2e-tests.md`?

**Comment by ishan16696** [comment]
> It looks fine, can you verify if you can run make ci-e2e-kind following docs/development/local-e2e-tests.md?

I don't get it, by running `make ci-e2e-kind` it will create a bucket using localstack right ? so, to tests this better to run druid e2e tests with AWS S3 and check whether the bucket created by public access or not
```
make \
  AWS_ACCESS_KEY_ID="abc" \
  AWS_SECRET_ACCESS_KEY="xyz" \
  AWS_REGION="eu-central-1" \
  KUBECONFIG="$HOME/.kube/config" \
  PROVIDERS="aws" \
  TEST_ID="some-test-id" \
  STEPS="setup,deploy,test,undeploy,cleanup" \
test-e2e
```

**Comment by abdasgupta** [comment]
> > It looks fine, can you verify if you can run make ci-e2e-kind following docs/development/local-e2e-tests.md?
> 
> I don't get it, by running `make ci-e2e-kind` it will create a bucket using localstack right ? so, to tests this better to run druid e2e tests with AWS S3 and check whether the bucket created by public access or not
> 
> ```
> make \
>   AWS_ACCESS_KEY_ID="abc" \
>   AWS_SECRET_ACCESS_KEY="xyz" \
>   AWS_REGION="eu-central-1" \
>   KUBECONFIG="$HOME/.kube/config" \
>   PROVIDERS="aws" \
>   TEST_ID="some-test-id" \
>   STEPS="setup,deploy,test,undeploy,cleanup" \
> test-e2e
> ```

As Shreyas was concerned that if the addition of policy would make any problem with localstack or not. That's why I asked him to run the PR once with `make ci-e2e-kind`.

**Comment by shreyas-s-rao** [comment]
I have already run the e2e tests that use AWS S3 bucket (`test-e2e`) as well as localstack S3 bucket (`ci-e2e-kind`), and both worked fine. The AWS S3 bucket was created with the expected bucket policy and blocked public access

**Review by ishan16696 — APPROVED** [review]
ok, thanks @shreyas-s-rao for PR and for testing it.

**Pull request merged**
