### PR TITLE
[WIP] Upgrade to go 1.22.2, g/g 1.92.2, and refresh indirect dependencies in go.mod

### LINKED ISSUE #778: Upgrade golang version to 1.22
** What you would like to be added:**
Upgrade golang version to 1.22.1

**Motivation (Why is this needed?):**
Use language improvements that have been introduced in 1.22. Also the https://github.com/gardener/etcd-druid/pull/777 depends upon this version. [gardener](https://github.com/gardener/gardener/blob/master/go.mod) has already moved to 1.22.1.

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**How to categorize this PR?**

/area quality dev-productivity
/kind impediment enhancement

**What this PR does / why we need it**:
Upgrades to go v1.22.2, and updates g/g dependency to v1.92.2 (latest version atm), and fix linter errors.

Additionally, indirect dependency `k8s.io/autoscaler` was at an old version, and was not compatible with gardener/gardener dependencies, causing improper imports when checking out both etcd-druid and gardener repos on the same machine. This has now been fixed, by refreshing all indirect dependencies, which caused `k8s.io/autoscaler` to be updated to `k8s.io/autoscaler/vertical-pod-autoscaler v1.0.0`.

**Which issue(s) this PR fixes**:
Fixes #778 #788 

**Special notes for your reviewer**:
/hold 
To be rebased after #777 is merged.
Ignore all commits expect the last 2, since this PR is based on #777 branch, not master (for ease of rebasing in the future).

**Release note**:

```other developer
Upgrade go to v1.22.2.
```

### CODE REVIEW

**Comment by renormalize** [comment]
Note: we could probably just run a regex to find all instances of where a new variable is declared inside the loop to deal with the `for` loop variable scoping pre go1.22.x.

Regex for `word := word`.

**Comment by renormalize** [comment]
@shreyas-s-rao go1.22.3 got released on 2024-05-07. If it's not too much effort for you, maybe the patch version could be changed from 2 to 3 in this PR to make use of security and bug fixes in the compiler, runtime and net/http.

**Comment by shreyas-s-rao** [comment]
@renormalize thanks for the information. I'll make both the changes you've suggested once #777 gets merged, because I anyway need to do some rebasing at that point of time, so I'll touch the code then.

**Comment by renormalize** [comment]
Yeah sure, I was just informing you in advance. Thanks!

**Comment by renormalize** [comment]
go1.22.4 has now been released. Once the refactor is merged, we could use go1.22.4 directly in this PR.

**Comment by ishan16696** [comment]
Closing this PR in favour of PR: https://github.com/gardener/etcd-druid/pull/834
/close

**Pull request closed without merging**
